Repository NumericalMathematics/DispersiveShallowWater.jl, pull requests merged in 2024-08, with the labels that each got.

#128 Add references to semidiscretizations in docstrings
  src/equations/bbm_bbm_1d.jl
  src/equations/bbm_bbm_variable_bathymetry_1d.jl
  src/equations/svaerd_kalisch_1d.jl
Labels: documentation

#127 implement Serre-Green-Naghdi equations for flat bathymetry
  Project.toml
  README.md
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_fourier.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_relaxation.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_upwind.jl
  src/DispersiveShallowWater.jl
  src/callbacks_step/analysis.jl
  src/equations/bbm_bbm_1d.jl
  src/equations/bbm_bbm_variable_bathymetry_1d.jl
  src/equations/equations.jl
  src/equations/serre_green_naghdi_flat_1d.jl
  src/equations/svaerd_kalisch_1d.jl
  src/semidiscretization.jl
  src/solver.jl
  test/Project.toml
  test/runtests.jl
  test/test_serre_green_naghdi_1d.jl
  test/test_unit.jl
Labels: enhancement

#134 Structure reference in docs in sections
  .github/workflows/CI.yml
  .github/workflows/DocPreviewCleanup.yml
  README.md
  docs/make.jl
  docs/src/development.md
  docs/src/index.md
  docs/src/overview.md
  docs/src/ref.md
  src/DispersiveShallowWater.jl
  src/equations/bbm_bbm_variable_bathymetry_1d.jl
  src/equations/equations.jl
  src/equations/svaerd_kalisch_1d.jl
  src/solver.jl
  test/test_bbm_bbm_1d.jl
Labels: documentation

#139 hyperbolic Serre-Green-Naghdi equations
  NEWS.md
  docs/src/overview.md
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_dingemans.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_manufactured.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_soliton.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_soliton_relaxation.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_well_balanced.jl
  src/DispersiveShallowWater.jl
  src/equations/equations.jl
  src/equations/hyperbolic_serre_green_naghdi_1d.jl
  src/equations/serre_green_naghdi_1d.jl
  src/semidiscretization.jl
  src/solver.jl
  src/visualization.jl
  test/runtests.jl
  test/test_hyperbolic_serre_green_naghdi_1d.jl
  test/test_svaerd_kalisch_1d.jl
  test/test_unit.jl
  test/test_visualization.jl
Labels: enhancement

#145 Simplify setting all files in subdirectory in docs
  docs/make.jl
  docs/src/ref.md
Labels: documentation

#146 Adapt Svärd-Kalisch equations to Serre-Green-Naghdi equations
  src/callbacks_step/analysis.jl
  src/callbacks_step/relaxation.jl
  src/equations/equations.jl
  src/equations/hyperbolic_serre_green_naghdi_1d.jl
  src/equations/serre_green_naghdi_1d.jl
  src/equations/svaerd_kalisch_1d.jl
  src/semidiscretization.jl
  test/test_unit.jl
Labels: refactoring

#147 Only one BBM-BBM equation struct for flat and variable bathymetry
  NEWS.md
  docs/make.jl
  docs/src/overview.md
  examples/bbm_bbm_1d/bbm_bbm_1d_basic.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_basic_reflecting.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_dg.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_dingemans.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_manufactured.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_relaxation.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_upwind_relaxation.jl
  examples/bbm_bbm_1d/bbm_bbm_1d_well_balanced.jl
  examples/bbm_bbm_variable_bathymetry_1d/bbm_bbm_variable_bathymetry_1d_basic.jl
  examples/bbm_bbm_variable_bathymetry_1d/bbm_bbm_variable_bathymetry_1d_dg_upwind_relaxation.jl
  examples/bbm_bbm_variable_bathymetry_1d/bbm_bbm_variable_bathymetry_1d_dingemans.jl
  examples/bbm_bbm_variable_bathymetry_1d/bbm_bbm_variable_bathymetry_1d_manufactured.jl
  examples/bbm_bbm_variable_bathymetry_1d/bbm_bbm_variable_bathymetry_1d_upwind_relaxation.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_conservation.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_dingemans.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_manufactured.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_soliton.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_soliton_relaxation.jl
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_well_balanced.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_conservation.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_dingemans.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_fourier.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_relaxation.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_upwind.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_well_balanced.jl
  examples/svaerd_kalisch_1d/svaerd_kalisch_1d_well_balanced.jl
  src/DispersiveShallowWater.jl
  src/callbacks_step/relaxation.jl
  src/equations/bbm_bbm_1d.jl
  src/equations/bbm_bbm_variable_bathymetry_1d.jl
  src/equations/equations.jl
  src/equations/hyperbolic_serre_green_naghdi_1d.jl
  src/equations/serre_green_naghdi_1d.jl
  src/equations/svaerd_kalisch_1d.jl
  src/semidiscretization.jl
  src/util.jl
  test/runtests.jl
  test/test_bbm_bbm_1d.jl
  test/test_bbm_bbm_variable_bathymetry_1d.jl
  test/test_hyperbolic_serre_green_naghdi_1d.jl
  test/test_serre_green_naghdi_1d.jl
  test/test_svaerd_kalisch_1d.jl
  test/test_unit.jl
  test/test_util.jl
Labels: breaking, refactoring
