Repository NumericalMathematics/DispersiveShallowWater.jl, pull requests merged in 2025-05, with the labels that each got.

#196 change default parameter set for Svärd-Kalisch equations
  NEWS.md
  docs/src/dispersion.md
  src/dispersion_relation.jl
  src/equations/svaerd_kalisch_1d.jl
  test/test_unit.jl
Labels: breaking

#201 Document `plot_initial = true`
  docs/src/overview.md
Labels: documentation

#203 Reducing allocations in relaxation
  src/callbacks_step/relaxation.jl
  src/semidiscretization.jl
Labels: performance

#206 Rename source term variables consistently
  src/equations/bbm_1d.jl
  src/equations/bbm_bbm_1d.jl
  src/equations/hyperbolic_serre_green_naghdi_1d.jl
  src/equations/kdv_1d.jl
  src/equations/serre_green_naghdi_1d.jl
  src/equations/svaerd_kalisch_1d.jl
Labels: consistency

#205 reflecting wall boundary conditions for Serre-Green-Naghdi
  Project.toml
  examples/serre_green_naghdi_1d/serre_green_naghdi_manufactured_reflecting.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_soliton_reflecting.jl
  src/DispersiveShallowWater.jl
  src/equations/equations.jl
  src/equations/serre_green_naghdi_1d.jl
  test/Project.toml
  test/test_serre_green_naghdi_1d.jl
Labels: enhancement
