Repository NumericalMathematics/DispersiveShallowWater.jl, pull requests merged in 2025-08, with the labels that each got.

#233 Improved documentation
  NEWS.md
  docs/make.jl
  docs/src/SBP_Operators.md
  docs/src/basic_example.md
  docs/src/callbacks.md
  docs/src/development.md
  docs/src/dingemans.md
  docs/src/index.md
  docs/src/overview.md
  docs/src/plotting.md
  docs/src/ref-trixibase.md
  docs/src/ref.md
  docs/src/solvers.md
  src/visualization.jl
Labels: documentation

#237 Changes to Dingemans initital condition
  benchmark/benchmarks.jl
  docs/src/basic_example.md
  docs/src/callbacks.md
  docs/src/dingemans.md
  docs/src/dispersion.md
  docs/src/overview.md
  docs/src/plotting.md
  docs/src/solvers.md
  examples/hyperbolic_serre_green_naghdi_1d/hyperbolic_serre_green_naghdi_dingemans.jl
  examples/serre_green_naghdi_1d/serre_green_naghdi_dingemans.jl
  src/equations/bbm_bbm_1d.jl
  src/equations/equations.jl
  src/equations/hyperbolic_serre_green_naghdi_1d.jl
  src/equations/serre_green_naghdi_1d.jl
  src/equations/svaerd_kalisch_1d.jl
  test/test_bbm_bbm_1d.jl
  test/test_hyperbolic_serre_green_naghdi_1d.jl
  test/test_serre_green_naghdi_1d.jl
  test/test_svaerd_kalisch_1d.jl
Labels: breaking, consistency

#238 Add comparison with experimental data to docs
  .github/workflows/Downgrade.yml
  NEWS.md
  Project.toml
  data/Dingemans.csv
  docs/Project.toml
  docs/src/dingemans.md
  docs/src/ref.md
  src/DispersiveShallowWater.jl
  src/experimental_data.jl
  src/util.jl
  test/test_unit.jl
Labels: documentation, enhancement
